
var mov = [
    ["acero","Ala de acero"],
    ["acero","Cabezahierro"],
    ["acero","Cola férrea"],
    ["acero","Cuerpopesado"],
    ["acero","Disparo espejo"],
    ["acero","Garra metal"],
    ["acero","Giro bola"],
    ["acero","Puño meteoro"],
    ["acero","Represión metal"],
    ["agua","Acua aro"],
    ["agua","Acua cola"],
    ["agua","Acua jet"],
    ["agua","Agua lodosa"],
    ["agua","Anegar"],
    ["agua","Buceo"],
    ["agua","Cascada"],
    ["agua","Danza lluvia"],
    ["agua","Escaldar"],
    ["agua","Hidrobomba"],
    ["agua","Hidrocañón"],
    ["agua","Hidropulso"],
    ["agua","Rayo burbuja"],
    ["agua","Refugio"],
    ["agua","Salmuera"],
    ["agua","Surf"],
    ["bicho","Cortefuria"],
    ["bicho","Doble rayo"],
    ["bicho","Megacuerno"],
    ["bicho","Picadura"],
    ["bicho","Rodillo púas"],
    ["bicho","Telaraña"],
    ["bicho","Tijera X"],
    ["bicho","Viento plata"],
    ["bicho","Zumbido"],
    ["dragon","Carga dragón"],
    ["dragon","Cola dragón"],
    ["dragon","Cometa draco"],
    ["dragon","Distorsión"],
    ["dragon","Dragoaliento"],
    ["dragon","Enfado"],
    ["dragon","Garra dragón"],
    ["dragon","Pulso dragón"],
    ["electrico","Bola voltio"],
    ["electrico","Chispazo"],
    ["electrico","Colmillo rayo"],
    ["electrico","Electrocañón"],
    ["electrico","Levitón"],
    ["electrico","Placaje eléctrico"],
    ["electrico","Puño trueno"],
    ["electrico","Rayo"],
    ["electrico","Rayo carga"],
    ["electrico","Voltiocambio"],
    ["electrico","Voltio cruel"],
    ["fantasma","Bola sombra"],
    ["fantasma","Garra umbría"],
    ["fantasma","Infortunio"],
    ["fantasma","Lengüetazo"],
    ["fantasma","Maldición"],
    ["fantasma","Pesadilla"],
    ["fantasma","Puño sombra"],
    ["fantasma","Viento aciago"],
    ["fuego","Anillo ígneo"],
    ["fuego","Bomba ígnea"],
    ["fuego","Colmillo ígneo"],
    ["fuego","Día soleado"],
    ["fuego","Envite ígneo"],
    ["fuego","Estallido"],
    ["fuego","Fuego fatuo"],
    ["fuego","Giro fuego"],
    ["fuego","Golpe calor"],
    ["fuego","Humareda"],
    ["fuego","Infierno"],
    ["fuego","Lanzallamas"],
    ["fuego","Llama azul"],
    ["fuego","Llama fusión"],
    ["fuego","Llamarada"],
    ["fuego","Lluvia ígnea"],
    ["fuego","Nitrocarga"],
    ["fuego","Onda ígnea"],
    ["fuego","Patada ígnea"],
    ["fuego","Pirotecnia"],
    ["fuego","Puño fuego"],
    ["fuego","Rueda fuego"],
    ["fuego","Sofoco"],
    ["fuego","V de fuego"],
    ["hielo","Alud"],
    ["hielo","Bola hielo"],
    ["hielo","Chuzos"],
    ["hielo","Colmillo hielo"],
    ["hielo","Frío polar"],
    ["hielo","Granizo"],
    ["hielo","Puño hielo"],
    ["hielo","Rayo aurora"],
    ["hielo","Rayo hielo"],
    ["hielo","Ventisca"],
    ["lucha","A bocajarro"],
    ["lucha","Demolición"],
    ["lucha","Esfera aural"],
    ["lucha","Fuerza bruta"],
    ["lucha","Gancho alto"],
    ["lucha","Llave giro"],
    ["lucha","Machada"],
    ["lucha","Onda certera"],
    ["lucha","Patada salto"],
    ["lucha","Puño certero"],
    ["lucha","Puño drenaje"],
    ["lucha","Puñodinámico"],
    ["lucha","Tajo cruzado"],
    ["normal","Adaptación"],
    ["normal","Agarrón"],
    ["normal","Alboroto"],
    ["normal","Alivio"],
    ["normal","Autodestrucción"],
    ["normal","Avivar"],
    ["normal","Azote"],
    ["normal","Batido"],
    ["normal","Bomba sónica"],
    ["normal","Bostezo"],
    ["normal","Campana cura"],
    ["normal","Canon"],
    ["normal","Canto"],
    ["normal","Canto mortal"],
    ["normal","Clonatipo"],
    ["normal","Conversión"],
    ["normal","Conversión 2"],
    ["normal","Copión"],
    ["normal","Cornada"],
    ["normal","Cuchillada"],
    ["normal","Derribo"],
    ["normal","Divide dolor"],
    ["normal","Doble filo"],
    ["normal","Eco voz"],
    ["normal","Escupir"],
    ["normal","Estrujón"],
    ["normal","Explosión"],
    ["normal","Fijar blanco"],
    ["normal","Garra brutal"],
    ["normal","Giga impacto"],
    ["normal","Giro rápido"],
    ["normal","Golpe cabeza"],
    ["normal","Golpe cuerpo"],
    ["normal","Guillotina"],
    ["normal","Hiper colmillo"],
    ["normal","Hiperrayo"],
    ["normal","Imagen"],
    ["normal","Luz lunar"],
    ["normal","Megapuño"],
    ["normal","Meteorobola"],
    ["normal","Metrónomo"],
    ["normal","Mimético"],
    ["normal","Pantallahumo"],
    ["normal","Perforador"],
    ["normal","Protección"],
    ["normal","Rapidez"],
    ["normal","Rastreo"],
    ["normal","Recuperación"],
    ["normal","Remolino"],
    ["normal","Reserva"],
    ["normal","Rizo defensa"],
    ["normal","Ronquido"],
    ["normal","Rugido"],
    ["normal","Sol matinal"],
    ["normal","Sonámbulo"],
    ["normal","Sorpresa"],
    ["normal","Superdiente"],
    ["normal","Supersónico"],
    ["normal","Tambor"],
    ["normal","Telépata"],
    ["normal","Tragar"],
    ["normal","Transformación"],
    ["normal","Treparrocas"],
    ["normal","Triataque"],
    ["normal","Última baza"],
    ["normal","Velo sagrado"],
    ["normal","Velocidad extrema"],
    ["normal","Viento cortante"],
    ["normal","Vozarrón"],
    ["normal","Yo primero"],
    ["planta","Aromaterapia"],
    ["planta","Arraigo"],
    ["planta","Astadrenaje"],
    ["planta","Bomba germen"],
    ["planta","Energibola"],
    ["planta","Espora"],
    ["planta","Esporagodón"],
    ["planta","Gigadrenado"],
    ["planta","Hoja aguda"],
    ["planta","Hoja mágica"],
    ["planta","Latigazo"],
    ["planta","Lluevehojas"],
    ["planta","Mazazo"],
    ["planta","Paralizador"],
    ["planta","Planta feroz"],
    ["planta","Rayo solar"],
    ["planta","Rizo algodón"],
    ["planta","Silbato"],
    ["planta","Síntesis"],
    ["planta","Somnífero"],
    ["psiquico","Bola neblina"],
    ["psiquico","Cabezazo zen"],
    ["psiquico","Cambia defensa"],
    ["psiquico","Cambia fuerza"],
    ["psiquico","Cambio banda"],
    ["psiquico","Capa mágica"],
    ["psiquico","Come sueños"],
    ["psiquico","Descanso"],
    ["psiquico","Espacio raro"],
    ["psiquico","Gravedad"],
    ["psiquico","Hipnosis"],
    ["psiquico","Intercambio"],
    ["psiquico","Isofuerza"],
    ["psiquico","Isoguardia"],
    ["psiquico","Manto espejo"],
    ["psiquico","Onda mental"],
    ["psiquico","Paranormal"],
    ["psiquico","Premonición"],
    ["psiquico","Psicocarga"],
    ["psiquico","Psíquico"],
    ["psiquico","Pulso cura"],
    ["psiquico","Teletransporte"],
    ["psiquico","Telequinesis"],
    ["roca","Antiaéreo"],
    ["roca","Avalancha"],
    ["roca","Desenrollar"],
    ["roca","Joya de luz"],
    ["roca","Poder pasado"],
    ["roca","Pulimento"],
    ["roca","Roca afilada"],
    ["roca","Romperrocas"],
    ["roca","Testarazo"],
    ["roca","Tormenta arena"],
    ["roca","Vastaguardia"],
    ["siniestro","Brecha negra"],
    ["siniestro","Juego sucio"],
    ["siniestro","Pulso noche"],
    ["siniestro","Pulso umbrío"],
    ["siniestro","Tajo umbrío"],
    ["siniestro","Triturar"],
    ["tierra","Excavar"],
    ["tierra","Fisura"],
    ["tierra","Hueso palo"],
    ["tierra","Huesomerang"],
    ["tierra","Magnitud"],
    ["tierra","Taladradora"],
    ["tierra","Terratemblor"],
    ["tierra","Terremoto"],
    ["tierra","Tierra viva"],
    ["veneno","Bomba lodo"],
    ["veneno","Cargatóxica"],
    ["veneno","Cola veneno"],
    ["veneno","Colmillo veneno"],
    ["veneno","Lanza mugre"],
    ["veneno","Onda tóxica"],
    ["veneno","Polvo veneno"],
    ["veneno","Puya nociva"],
    ["veneno","Veneno X"],
    ["volador","Acróbata"],
    ["volador","Aerochorro"],
    ["volador","Aire afilado"],
    ["volador","Ataque aéreo"],
    ["volador","Ataque ala"],
    ["volador","Bote"],
    ["volador","Golpe aéreo"],
    ["volador","Movimiento espejo"],
    ["volador","Pájaro osado"],
    ["volador","Pico taladro"],
    ["volador","Picoteo"],
    ["volador","Respiro"],
    ["volador","Tajo aéreo"],
    ["volador","Vendaval"],
    ["volador","Viento afin"],
    ["volador","Vuelo"],
    ["normal","Deslumbrar"],
    ["veneno","Enrosque"],
    ["veneno","Picotazo venenoso"],
    ["electrico","Trueno"],
    ["normal","Portazo"],
    ["psiquico","Agilidad"],
    ["siniestro","Afilagarras"],
    ["acero","Bomba imán"],
    ["acero","Foco resplandor"],
    ["electrico","Onda trueno"],
];

